[package]
name = "runtime-fuzzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3"
codec = { package = "parity-scale-codec", version = "3.1.5", default-features = false, features = [
    "derive",
] }
rand = "0.8.5"
#sp-runtime = { version = "30.0.1", default-features = false }
wasmi = "0.31.1"
wat = "1.0.82"

[features]
default = ["std"]
std = ["codec/std"]
